CREATE PROC FI_SP_ConsCliente
    @ID BIGINT = NULL 
AS
BEGIN
    IF(@ID IS NULL)
        SELECT NOME, SOBRENOME, NACIONALIDADE, CPF, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID FROM CLIENTES WITH(NOLOCK)
    ELSE
        SELECT NOME, SOBRENOME, NACIONALIDADE, CPF, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID FROM CLIENTES WITH(NOLOCK) WHERE ID = @ID
END